server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tanmu_video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    prefix: 'tanmu::'
    expired-seconds: 3600


logging:
  level:
    root: info
    com.video.tanmu.dao: debug
  file:
    name: log/log.log
