server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/tanmu_video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123

logging:
  level:
    root: info
    com.video.tanmu.dao: debug
  file:
    name: ./tanmu_log.log
